version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-crud-go
    environment:
      POSTGRES_DB: crud-basic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-crud-go
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  myapp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres-crud-go
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin1234
      - DB_NAME=crud-basic
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: